version: '2'

services:
  web:
    build: .
    volumes:
      - .:/msugradesapI
    ports:
      - "8000:8000"
      - "443:443"
    network_mode: host

  nginx:
    build: ./nginx
    container_name: nginx
    environment:
      - SERVER_NAME=3.14.6.168
    restart: always
    network_mode: host
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/etc/nginx/certs