version: '3'

services:
  web:
    build: .
    volumes:
      - .:/msugradesapi
    ports:
      - "8000:8000"
    network_mode: host

  nginx:
    build: ./nginx
    container_name: nginx
    environment:
      - SERVER_NAME=3.14.6.168
    restart: always
    network_mode: host